//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.WebFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPEDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPEDetail()
        {
            this.CPEReviews = new HashSet<CPEReview>();
        }
    
        public System.Guid Id { get; set; }
        public decimal SRNumber { get; set; }
        public string ReviewMonth { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public string EngineerName { get; set; }
        public string EngManager { get; set; }
        public string PODName { get; set; }
        public Nullable<System.DateTime> SRCreatedDate { get; set; }
        public Nullable<decimal> SRDTS { get; set; }
        public string QoS { get; set; }
        public Nullable<decimal> SRDTC { get; set; }
        public string IRMissed { get; set; }
        public string SupportOffering { get; set; }
        public string SupportServiceLevel { get; set; }
        public string CurrentOwnerGroup { get; set; }
        public string SurveyMonth { get; set; }
        public string QualityAnalystName { get; set; }
        public string SRClosedMonth { get; set; }
        public string DeliveryRegion { get; set; }
        public string AreaName { get; set; }
        public string SurveyVerbatim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPEReview> CPEReviews { get; set; }
    }
}
