//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.WebFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPEReview
    {
        public System.Guid Id { get; set; }
        public System.Guid CPEDetailsId { get; set; }
        public Nullable<decimal> SRNumber { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public string QAAssesment { get; set; }
        public string PODManagerComment { get; set; }
        public string PODLeadAction { get; set; }
        public string ActionStatus { get; set; }
    
        public virtual CPEDetail CPEDetail { get; set; }
    }
}
