//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.WebFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyL3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxonomyL3()
        {
            this.TaxonomyL4 = new HashSet<TaxonomyL4>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> L2_Id { get; set; }
        public string Value { get; set; }
    
        public virtual TaxonomyL2 TaxonomyL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxonomyL4> TaxonomyL4 { get; set; }
    }
}
