//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.WebFrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyL2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxonomyL2()
        {
            this.TaxonomyL3 = new HashSet<TaxonomyL3>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> L1_Id { get; set; }
        public string Value { get; set; }
    
        public virtual TaxonomyL1 TaxonomyL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxonomyL3> TaxonomyL3 { get; set; }
    }
}
